import { AC, paperGrain } from '@/components/ac-primitives'

const FF = { serif: 'var(--font-fraunces)', hand: 'var(--font-caveat)' }

const h2 = { fontFamily: FF.serif, fontStyle: 'italic' as const, fontSize: 26, fontWeight: 700, color: AC.ink, margin: '40px 0 10px' }
const body = { fontFamily: FF.serif, fontSize: 15, lineHeight: 1.8, color: AC.ink, opacity: 0.82, margin: '0 0 16px' }

export default function TermsPage() {
  return (
    <div style={{ background: AC.parchment, minHeight: '100vh', ...paperGrain }}>
      <div style={{ maxWidth: 740, margin: '0 auto', padding: 'clamp(48px, 8vw, 88px) clamp(24px, 6vw, 48px)' }}>

        <span style={{ fontFamily: FF.hand, fontSize: 20, color: AC.rasp, display: 'block', marginBottom: 8 }}>— the fine print —</span>
        <h1 style={{ fontFamily: FF.serif, fontStyle: 'italic', fontSize: 'clamp(40px, 7vw, 72px)', fontWeight: 900, color: AC.ink, margin: '0 0 8px', lineHeight: 1 }}>Terms of Service</h1>
        <p style={{ fontFamily: FF.serif, fontSize: 13, color: `${AC.ink}60`, margin: '0 0 48px' }}>Last updated: May 1, 2026</p>

        <p style={body}>By using the Legendairy website and placing an order, you agree to these terms. Please read them — they're short and written in plain English.</p>

        <h2 style={h2}>Who we are</h2>
        <p style={body}>Legendairy is a small-batch, made-to-order artisan ice cream company based in Massachusetts. We generate one-of-one ice cream recipes using AI based on prompts you provide, then churn and ship them directly to you.</p>

        <h2 style={h2}>Using the service</h2>
        <p style={body}>You must be at least 13 years old to use Legendairy. By placing an order, you confirm that the shipping address you provide is accurate and that you are authorized to use the payment method provided.</p>
        <p style={body}>The flavor recipes generated by our AI are created uniquely for each prompt. We reserve the right to decline any prompt that is offensive, unlawful, or otherwise inappropriate.</p>

        <h2 style={h2}>Orders and payment</h2>
        <p style={body}>All prices are in USD. Orders are confirmed only after successful payment processing through Stripe. We reserve the right to cancel any order at our discretion, in which case a full refund will be issued.</p>
        <p style={body}>Because each order is made specifically for you, we begin production the morning after your order is placed. Please review our <a href="/refunds" style={{ color: AC.rasp }}>Refund & Cancellation Policy</a> before ordering.</p>

        <h2 style={h2}>Allergens</h2>
        <p style={body}>Our kitchen works with common allergens including milk, eggs, wheat, tree nuts, peanuts, and soy. While we take care to keep batches separated, we cannot guarantee any product is free from cross-contact. By placing an order, you acknowledge this risk. If you have a severe allergy, please do not order.</p>

        <h2 style={h2}>Intellectual property</h2>
        <p style={body}>The flavor recipes, names, and copy generated for your order belong to you for personal use. The Legendairy brand, website design, and underlying technology remain our property.</p>

        <h2 style={h2}>Limitation of liability</h2>
        <p style={body}>Legendairy's liability is limited to the value of your order. We are not responsible for indirect, incidental, or consequential damages arising from use of the service or consumption of our products, to the fullest extent permitted by Massachusetts law.</p>

        <h2 style={h2}>Governing law</h2>
        <p style={body}>These terms are governed by the laws of the Commonwealth of Massachusetts. Any disputes will be resolved in the courts of Massachusetts.</p>

        <h2 style={h2}>Changes to these terms</h2>
        <p style={body}>We may update these terms from time to time. Continued use of the service after changes are posted constitutes acceptance of the revised terms.</p>

        <h2 style={h2}>Contact</h2>
        <p style={body}>Questions? Email us at <a href="mailto:hello@legendairyicecream.com" style={{ color: AC.rasp }}>hello@legendairyicecream.com</a>.</p>

        <div style={{ borderTop: `1px solid ${AC.ink}20`, marginTop: 48, paddingTop: 24 }}>
          <p style={{ fontFamily: FF.serif, fontSize: 13, color: `${AC.ink}45`, margin: 0 }}>Legendairy · Massachusetts · hello@legendairyicecream.com</p>
        </div>

      </div>
    </div>
  )
}
